"""empty message

Revision ID: 806c334398da
Revises: 4d30c8b34f94
Create Date: 2026-01-22 02:13:34.280881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '806c334398da'
down_revision = '4d30c8b34f94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.String(length=140), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('content')

    # ### end Alembic commands ###
